name: Keep Backend Awake
on:
  schedule:
    - cron: "*/1 * * * *" # Every 1 minutes
  workflow_dispatch: # Allows manual button click
  push: # Runs immediately when you push this file
    branches:
      - main

jobs:
  ping_server:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend
        run: |
          curl -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" https://foss-club.onrender.com